# Generated by Django 5.0.1 on 2025-12-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPP', '0004_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(max_length=200),
        ),
    ]
