# Generated by Django 5.2.8 on 2025-11-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='CalculadoraSettings',
        ),
        migrations.DeleteModel(
            name='GradeEntry',
        ),
    ]
