# Generated by Django 5.2.8 on 2025-11-26 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='ramo',
        ),
        migrations.RemoveField(
            model_name='ramo',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.JSONField(default=list)),
                ('exam_note', models.FloatField(blank=True, null=True)),
                ('exam_percent', models.FloatField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.semester')),
            ],
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Ramo',
        ),
        migrations.DeleteModel(
            name='Semestre',
        ),
    ]
