# Generated by Django 5.2.8 on 2025-11-26 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_semester_user_ramo_delete_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramo',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='ramo',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='ramo',
            name='nota_aprobar',
        ),
        migrations.RemoveField(
            model_name='ramo',
            name='notas',
        ),
        migrations.AddField(
            model_name='ramo',
            name='tiene_examen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('porcentaje', models.FloatField()),
                ('es_examen', models.BooleanField(default=False)),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.ramo')),
            ],
        ),
    ]
