# Generated by Django 5.2.8 on 2025-11-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ramo_creado_remove_ramo_examen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramo',
            name='tiene_examen',
        ),
        migrations.AddField(
            model_name='ramo',
            name='examen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ramo',
            name='notas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
