# Generated by Django 5.2.8 on 2025-11-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ramo_tiene_examen_ramo_examen_ramo_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='examen',
            field=models.JSONField(default=dict),
        ),
    ]
